// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU4CLqmlyUaE6fTLgl5lbVief2ynnJsQw',
    appId: '1:281645452187:web:63e880954dd69188982f3e',
    messagingSenderId: '281645452187',
    projectId: 'larajek-c61af',
    authDomain: 'larajek-c61af.firebaseapp.com',
    storageBucket: 'larajek-c61af.firebasestorage.app',
    measurementId: 'G-S5ZVGGB95G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JQoRyuXTl0mhy3w1bGw64XLXgNZi5sI',
    appId: '1:281645452187:android:3822a173a083641d982f3e',
    messagingSenderId: '281645452187',
    projectId: 'larajek-c61af',
    storageBucket: 'larajek-c61af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSMY11kOW9STibI_C9HYWOn2NrQbujwyk',
    appId: '1:281645452187:ios:bc11b15c0263ba82982f3e',
    messagingSenderId: '281645452187',
    projectId: 'larajek-c61af',
    storageBucket: 'larajek-c61af.firebasestorage.app',
    iosBundleId: 'com.example.laraJek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSMY11kOW9STibI_C9HYWOn2NrQbujwyk',
    appId: '1:281645452187:ios:bc11b15c0263ba82982f3e',
    messagingSenderId: '281645452187',
    projectId: 'larajek-c61af',
    storageBucket: 'larajek-c61af.firebasestorage.app',
    iosBundleId: 'com.example.laraJek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU4CLqmlyUaE6fTLgl5lbVief2ynnJsQw',
    appId: '1:281645452187:web:ea01aea5c341c552982f3e',
    messagingSenderId: '281645452187',
    projectId: 'larajek-c61af',
    authDomain: 'larajek-c61af.firebaseapp.com',
    storageBucket: 'larajek-c61af.firebasestorage.app',
    measurementId: 'G-375BX8LBW5',
  );

}